backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: static/uploads
public_folder: /uploads
site_url: https://www.seabothsides.com

collections:
  - name: 'options'
    label: 'Options'
    format: 'frontmatter'
    editor:
      preview: false
    files:
      - label: 'Options list'
        name: 'options'
        file: 'content/options.md'
        fields:
          - label: Categories
            name: categories
            widget: object
            fields:
              - { label: 'Blog category', name: 'blog', widget: 'list' }
          - label: Tags
            name: tags
            widget: object
            fields:
              - { label: 'Blog tags', name: 'blog', widget: 'list' }
          - label: Series
            name: series
            widget: object
            fields:
              - { label: 'Blog series', name: 'blog', widget: 'list' }

  - name: 'authors'
    label: 'Authors'
    format: 'frontmatter'
    editor:
      preview: false
    files:
      - label: 'Authors list'
        name: 'authors'
        file: 'content/authors.md'
        fields:
          - label: Authors
            name: authors
            widget: list
            fields:
              - label: Author
                name: author
                widget: object
                fields:
                  - { label: 'Author name', name: 'name', widget: 'string' }
                  - { label: Author img, name: img, widget: image }
                  - { label: Author bio, name: bio, widget: string }
                  - {
                      label: Author about,
                      name: about,
                      widget: markdown,
                      required: false,
                    }

  - name: pages
    label: Pages
    format: frontmatter
    editor:
      preview: false
    files:
      - label: Landing
        name: landing
        file: content/pages/landing.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - label: Section
            name: section
            widget: list
            fields:
              - label: Content
                name: content
                widget: object
                fields:
                  - { label: Feature image, name: image, widget: image }
                  - { label: Title, name: title, widget: string }
                  - { label: Content, name: caption, widget: string }
                  - label: Button
                    name: button
                    widget: object
                    fields:
                      - { label: Button content, name: name, widget: string }
                      - {
                          label: External-URL,
                          name: eurl,
                          widget: string,
                          required: false,
                        }
                      - {
                          label: internal-URL,
                          name: iurl,
                          widget: string,
                          required: false,
                        }

  - name: 'blog'
    label: 'Blog post'
    format: 'frontmatter'
    folder: 'content/blog'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - label: Author
        name: author
        widget: object
        fields:
          - {
              label: Name,
              name: name,
              widget: string,
              default: Ricardo Calcina,
            }
          - {
              label: Image,
              name: img,
              widget: image,
              default: /uploads/author-img-ric.png,
            }
      - label: 'Categories'
        name: 'categories'
        widget: 'relation'
        collection: 'options'
        file: 'options'
        required: false
        value_field: 'categories.blog.*'
        search_fields: ['categories.blog.*']
        multiple: true
      - label: 'Tags'
        name: 'tags'
        widget: 'relation'
        collection: 'options'
        file: 'options'
        required: false
        value_field: 'tags.blog.*'
        search_fields: ['tags.blog.*']
        multiple: true
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
